from enum import Enum

class Feature(Enum):
    # CORE FEATURES
    AUTHENTICATION = "AUTHENTICATION"
    PROFILE_MANAGEMENT = "PROFILE_MANAGEMENT"
    ACCOUNT_COMPLETION = "ACCOUNT_COMPLETION"
    CHANGE_PASSWORD = "CHANGE_PASSWORD"
    LOGOUT = "LOGOUT"
    VIEW_NOTIFICATIONS = "VIEW_NOTIFICATIONS"
    DELETE_ACCOUNT = "DELETE_ACCOUNT"

    # GUEST FEATURES
    BROWSE_VEHICLES = "BROWSE_VEHICLES"
    ADVANCED_SEARCH = "ADVANCED_SEARCH"
    REGISTER = "REGISTER"
    LOGIN = "LOGIN"

    # BUYER FEATURES
    ADD_ITEM = "ADD_ITEM"
    REMOVE_ITEM = "REMOVE_ITEM"
    VIEW_CART = "VIEW_CART"
    CLEAR_CART = "CLEAR_CART"
    CALCULATE_TOTAL = "CALCULATE_TOTAL"

    ADD_TO_WISHLIST = "ADD_TO_WISHLIST"
    REMOVE_FROM_WISHLIST = "REMOVE_FROM_WISHLIST"
    VIEW_WISHLIST = "VIEW_WISHLIST"
    CLEAR_WISHLIST = "CLEAR_WISHLIST"
    FOLLOW_SELLER = "FOLLOW_SELLER"

    CHECKOUT = "CHECKOUT"
    ORDER_HISTORY = "ORDER_HISTORY"
    FEEDBACK_CONTACT = "FEEDBACK_CONTACT"

    # SELLER FEATURES
    ADD_VEHICLE = "ADD_VEHICLE"
    UPDATE_VEHICLE = "UPDATE_VEHICLE"
    REMOVE_VEHICLE = "REMOVE_VEHICLE"
    VIEW_MY_VEHICLES = "VIEW_MY_VEHICLES"
    VIEW_SALES = "VIEW_SALES"
    ORDER_FULFILLMENT = "ORDER_FULFILLMENT"

    VIEW_EARNINGS = "VIEW_EARNINGS"
    WITHDRAW_MONEY = "WITHDRAW_MONEY"

    EDIT_SHOP_INFO = "EDIT_SHOP_INFO"

    # ADMIN FEATURES
    SYSTEM_DASHBOARD = "SYSTEM_DASHBOARD"
    USER_MANAGEMENT = "USER_MANAGEMENT"
    VEHICLE_MODERATION = "VEHICLE_MODERATION"
    ORDER_MONITORING = "ORDER_MONITORING"
    FEEDBACK_MODERATION = "FEEDBACK_MODERATION"
    SYSTEM_SETTINGS = "SYSTEM_SETTINGS"

    VIEW_USERS = "VIEW_USERS"
    CHANGE_USER_ROLE = "CHANGE_USER_ROLE"
    DEACTIVATE_USER = "DEACTIVATE_USER"
    DELETE_USER = "DELETE_USER"

    VIEW_ALL_VEHICLES = "VIEW_ALL_VEHICLES"
    APPROVE_REJECT_VEHICLE = "APPROVE_REJECT_VEHICLE"

    # FEATURES REQUIRING COMPLETE PROFILE
    SELL_VEHICLE = "SELL_VEHICLE"
    RECEIVE_PAYMENTS = "RECEIVE_PAYMENTS"

class SpecialFeature(Enum):
    VEHICLE_DETAILS = "VEHICLE_DETAILS"

# Core features مشتركة لكل الأدوار ماعدا guest
CORE_FEATURES = [
    Feature.AUTHENTICATION,
    Feature.PROFILE_MANAGEMENT,
    Feature.ACCOUNT_COMPLETION,
    Feature.CHANGE_PASSWORD,
    Feature.LOGOUT,
    Feature.VIEW_NOTIFICATIONS,
    Feature.DELETE_ACCOUNT,
]

ROLE_FEATURES = {
    "GUEST": [
        Feature.BROWSE_VEHICLES,
        Feature.ADVANCED_SEARCH,
        Feature.REGISTER,
        Feature.LOGIN,
        Feature.LOGOUT,
    ],
    
    "BUYER": [
        Feature.BROWSE_VEHICLES,
        Feature.ADVANCED_SEARCH,
        Feature.ADD_ITEM,
        Feature.REMOVE_ITEM,
        Feature.VIEW_CART,
        Feature.CLEAR_CART,
        Feature.CALCULATE_TOTAL,
        Feature.ADD_TO_WISHLIST,
        Feature.REMOVE_FROM_WISHLIST,
        Feature.VIEW_WISHLIST,
        Feature.CLEAR_WISHLIST,
        Feature.FOLLOW_SELLER,
        Feature.CHECKOUT,
        Feature.ORDER_HISTORY,
        Feature.FEEDBACK_CONTACT,
    ],

    "SELLER": [
        Feature.ADD_VEHICLE,
        Feature.UPDATE_VEHICLE,
        Feature.REMOVE_VEHICLE,
        Feature.VIEW_MY_VEHICLES,
        Feature.VIEW_SALES,
        Feature.ORDER_FULFILLMENT,
        Feature.VIEW_EARNINGS,
        Feature.WITHDRAW_MONEY,
        Feature.EDIT_SHOP_INFO,
    ],

    "ADMIN": [
        Feature.SYSTEM_DASHBOARD,
        Feature.USER_MANAGEMENT,
        Feature.VEHICLE_MODERATION,
        Feature.ORDER_MONITORING,
        Feature.FEEDBACK_MODERATION,
        Feature.SYSTEM_SETTINGS,
        Feature.VIEW_USERS,
        Feature.CHANGE_USER_ROLE,
        Feature.DEACTIVATE_USER,
        Feature.DELETE_USER,
        Feature.VIEW_ALL_VEHICLES,
        Feature.APPROVE_REJECT_VEHICLE,
        Feature.REMOVE_VEHICLE,
    ],
}

def get_features_for_role(role_name):
    if role_name.upper() == "GUEST":
        return ROLE_FEATURES["GUEST"]
    return CORE_FEATURES + ROLE_FEATURES.get(role_name.upper(), [])
